/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.projeto.pdv.view;

import br.com.projeto.pdv.dao.ItemVendaDAO;
import br.com.projeto.pdv.dao.ProdutoDAO;
import br.com.projeto.pdv.dao.VendaDAO;
import br.com.projeto.pdv.model.ClienteModel;
import br.com.projeto.pdv.model.ItemVendaModel;
import br.com.projeto.pdv.model.ProdutoModel;
import br.com.projeto.pdv.model.VendaModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lex
 */
public class PagamentoView extends JDialog {

    ClienteModel cliente = new ClienteModel();
    DefaultTableModel carrinhoPagamento;
    double pcartao, pdinheiro, totalPago, totalVenda, troco, volta;
    int clienteId;

    /**
     * Creates new form PagamentoView
     */
    public PagamentoView() {
        initComponents();
        this.setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelCodigo1 = new javax.swing.JLabel();
        jLabelCodigo3 = new javax.swing.JLabel();
        jLabelCodigo4 = new javax.swing.JLabel();
        txtDinheiro = new javax.swing.JTextField();
        txtTroco = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtCartao = new javax.swing.JTextField();
        btnFinalizarVenda = new javax.swing.JButton();
        btnVoltarPdv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pagamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelCodigo.setText("Dinheiro:");

        jLabelCodigo1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelCodigo1.setText("Cartão:");

        jLabelCodigo3.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabelCodigo3.setForeground(new java.awt.Color(51, 204, 0));
        jLabelCodigo3.setText("Troco:");

        jLabelCodigo4.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabelCodigo4.setText("Total:");

        txtDinheiro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtDinheiro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDinheiroFocusLost(evt);
            }
        });
        txtDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDinheiroActionPerformed(evt);
            }
        });

        txtTroco.setEditable(false);
        txtTroco.setBackground(new java.awt.Color(255, 255, 255));
        txtTroco.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        txtTroco.setForeground(new java.awt.Color(0, 204, 51));
        txtTroco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTrocoFocusGained(evt);
            }
        });
        txtTroco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTrocoMouseClicked(evt);
            }
        });
        txtTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrocoActionPerformed(evt);
            }
        });

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N

        txtCartao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCartao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCartaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCartaoFocusLost(evt);
            }
        });
        txtCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCartaoActionPerformed(evt);
            }
        });

        btnFinalizarVenda.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnFinalizarVenda.setText("Finalizar Venda");
        btnFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVendaActionPerformed(evt);
            }
        });

        btnVoltarPdv.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnVoltarPdv.setText("Voltar ao PDV");
        btnVoltarPdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarPdvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCodigo)
                            .addComponent(jLabelCodigo1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCodigo3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCodigo4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnFinalizarVenda))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnVoltarPdv)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo1)
                    .addComponent(txtCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodigo4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo3)
                    .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnFinalizarVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltarPdv)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVendaActionPerformed
        // TODO add your handling code here:
        volta = Double.parseDouble(txtTroco.getText());
        if (volta < 0) {
            JOptionPane.showMessageDialog(null, "valores incorretos!");
        } else {
            calculaTroco();

            //Dados do Cliente
            VendaModel objv = new VendaModel();
            objv.setCliente(cliente);

            //Pegando a data da Venda
            Date agora = new Date();
            SimpleDateFormat dataEua = new SimpleDateFormat("yyyy-MM-dd HH:mm");
            String dataMysql = dataEua.format(agora);
            objv.setDataVenda(dataMysql);

            //Total da venda.
            objv.setTotalVenda(totalVenda);

            VendaDAO vDao = new VendaDAO();
            vDao.cadastrarVenda(objv);

            objv.setId(vDao.retornaUltimaVenda());

            //Cadastrando os produtos da Venda na Tabela  itensVenda
            for (int i = 0; i < carrinhoPagamento.getRowCount(); i++) {
                int qtd_estoque, qtd_comprada, qtd_atualizada;
                ProdutoDAO dao = new ProdutoDAO();
                ProdutoModel objp = new ProdutoModel();
                ItemVendaModel item = new ItemVendaModel();

                item.setVenda(objv);

                objp.setId(Integer.parseInt(carrinhoPagamento.getValueAt(i, 0).toString()));

                item.setProduto(objp);
                item.setQtd(Integer.parseInt(carrinhoPagamento.getValueAt(i, 2).toString()));
                item.setSubTotal(Double.parseDouble(carrinhoPagamento.getValueAt(i, 4).toString()));

                //Baixa no estoque de Produtos
                qtd_estoque = dao.retornaEstoqueAtual(objp.getId());
                qtd_comprada = Integer.parseInt(carrinhoPagamento.getValueAt(i, 2).toString());
                qtd_atualizada = qtd_estoque - qtd_comprada;
                dao.baixaEstoque(objp.getId(), qtd_atualizada);

                ItemVendaDAO itemDao = new ItemVendaDAO();
                itemDao.cadastraItem(item);
            }
            JOptionPane.showMessageDialog(null, "Venda Registrada com Sucesso para o Cliente: " + cliente.getNome());
            VendaView pdv = new VendaView();
            pdv.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnFinalizarVendaActionPerformed

    private void btnVoltarPdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarPdvActionPerformed
        // TODO add your handling code here:
        VendaView pdv = new VendaView();

    }//GEN-LAST:event_btnVoltarPdvActionPerformed

    private void txtTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrocoActionPerformed
        // TODO add your handling code here:
        calculaTroco();
    }//GEN-LAST:event_txtTrocoActionPerformed

    private void txtDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDinheiroActionPerformed
        // TODO add your handling code here:
        calculaTroco();
    }//GEN-LAST:event_txtDinheiroActionPerformed

    private void txtCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCartaoActionPerformed
        // TODO add your handling code here:
        calculaTroco();
    }//GEN-LAST:event_txtCartaoActionPerformed

    private void txtTrocoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTrocoFocusGained
        // TODO add your handling code here:
        calculaTroco();
    }//GEN-LAST:event_txtTrocoFocusGained

    private void txtTrocoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTrocoMouseClicked
        // TODO add your handling code here:
        calculaTroco();
    }//GEN-LAST:event_txtTrocoMouseClicked

    private void txtDinheiroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDinheiroFocusLost
        // TODO add your handling code here:
        calculaTroco();
    }//GEN-LAST:event_txtDinheiroFocusLost

    private void txtCartaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCartaoFocusGained
        // TODO add your handling code here:
        calculaTroco();
    }//GEN-LAST:event_txtCartaoFocusGained

    private void txtCartaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCartaoFocusLost
        // TODO add your handling code here:
        calculaTroco();
    }//GEN-LAST:event_txtCartaoFocusLost

    private void calculaTroco() {
        pcartao = Double.parseDouble(txtCartao.getText());
        pdinheiro = Double.parseDouble(txtDinheiro.getText());
        totalVenda = Double.parseDouble(txtTotal.getText());
        totalPago = pdinheiro + pcartao;
        troco = totalPago - totalVenda;
        txtTroco.setText(String.valueOf(troco));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagamentoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarVenda;
    private javax.swing.JButton btnVoltarPdv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCodigo1;
    private javax.swing.JLabel jLabelCodigo3;
    private javax.swing.JLabel jLabelCodigo4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txtCartao;
    public javax.swing.JTextField txtDinheiro;
    public javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTroco;
    // End of variables declaration//GEN-END:variables
}
