/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.projeto.pdv.view;

import br.com.projeto.pdv.dao.ClienteDAO;
import br.com.projeto.pdv.dao.ProdutoDAO;
import br.com.projeto.pdv.model.ClienteModel;
import br.com.projeto.pdv.model.ProdutoModel;
import br.com.projeto.pdv.util.Utilitarios;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lex
 */
public class VendaView extends JDialog {

    ClienteModel obj = new ClienteModel();

    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    double total, subtotal, preco;
    int qtd;
    DefaultTableModel carrinhoVenda;

    public void listarClientes() {
        ClienteDAO dao = new ClienteDAO();
        List<ClienteModel> lista = dao.listarCliente();
        DefaultTableModel dados = (DefaultTableModel) TabelaClientes.getModel();
        dados.setNumRows(0);

        lista.forEach(c -> {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCpf()
            });
        });
    }

    public void listarProdutos() {
        ProdutoDAO dao = new ProdutoDAO();
        List<ProdutoModel> lista = dao.listarProduto();
        DefaultTableModel dados = (DefaultTableModel) TabelaListaProdutoss.getModel();
        dados.setNumRows(0);

        lista.forEach(c -> {
            dados.addRow(new Object[]{
                c.getId(),
                c.getDescricao(),
                c.getPreco(),
                c.getQtd_estoque()

            });
        });
    }

    /**
     * Creates new form clienteView
     */
    public VendaView() {
        initComponents();
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PainelGeral = new javax.swing.JTabbedPane();
        PainelVenda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaItens = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabelCpf2 = new javax.swing.JLabel();
        txtTotalDaVenda = new javax.swing.JTextField();
        btnFinalizarCompra = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        PainelProduto = new javax.swing.JPanel();
        jLabelCpf1 = new javax.swing.JLabel();
        jLabelNome3 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtCodigoProduto = new javax.swing.JTextField();
        jLabelNome4 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabelNome5 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btnPesquisarProduto = new javax.swing.JButton();
        btnAdiionarItem = new javax.swing.JButton();
        btnListaProdutos = new javax.swing.JButton();
        btnRemoverItem = new javax.swing.JButton();
        txtPrecoFormatted = new javax.swing.JFormattedTextField();
        PainelCliente = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        txtDataVenda = new javax.swing.JTextField();
        jLabelCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabelNome1 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        btnPesquisarCliente = new javax.swing.JButton();
        btnListaClientes = new javax.swing.JButton();
        jLabelNome2 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        PainelClientes = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtPesquisarClientess = new javax.swing.JTextField();
        btnPesquisarClientess = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaClientes = new javax.swing.JTable();
        btnAtualizarListaClientess = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        PainelProdutos = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtpesquisaProdutoss = new javax.swing.JTextField();
        btnPesquisarProdutoss = new javax.swing.JButton();
        btnAtualizarListaProdutoss = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelaListaProdutoss = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        PainelLogo.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ponto de Vendas");

        javax.swing.GroupLayout PainelLogoLayout = new javax.swing.GroupLayout(PainelLogo);
        PainelLogo.setLayout(PainelLogoLayout);
        PainelLogoLayout.setHorizontalGroup(
            PainelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(357, 357, 357))
        );
        PainelLogoLayout.setVerticalGroup(
            PainelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        PainelGeral.setBackground(new java.awt.Color(255, 255, 255));

        PainelVenda.setBackground(new java.awt.Color(255, 255, 255));
        PainelVenda.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrinho de Compras"));

        TabelaItens.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        TabelaItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código:", "Produto:", "Quant.", "Preço:", "Subtotal:"
            }
        ));
        TabelaItens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaItensMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaItens);
        if (TabelaItens.getColumnModel().getColumnCount() > 0) {
            TabelaItens.getColumnModel().getColumn(0).setPreferredWidth(50);
            TabelaItens.getColumnModel().getColumn(1).setPreferredWidth(200);
            TabelaItens.getColumnModel().getColumn(2).setPreferredWidth(7);
            TabelaItens.getColumnModel().getColumn(3).setPreferredWidth(30);
            TabelaItens.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Total da Venda"));

        jLabelCpf2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelCpf2.setText("TOTAL DA VENDA: R$");

        txtTotalDaVenda.setEditable(false);
        txtTotalDaVenda.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCpf2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalDaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalDaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCpf2))
                .addContainerGap())
        );

        btnFinalizarCompra.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnFinalizarCompra.setText("Finalizar Compra");
        btnFinalizarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizarCompraMouseClicked(evt);
            }
        });
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        PainelProduto.setBackground(new java.awt.Color(255, 255, 255));
        PainelProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações dos Produtos"));

        jLabelCpf1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCpf1.setText("Código:");

        jLabelNome3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNome3.setText("Descrição:");

        txtDescricao.setEditable(false);
        txtDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtCodigoProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProdutoActionPerformed(evt);
            }
        });
        txtCodigoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoProdutoKeyPressed(evt);
            }
        });

        jLabelNome4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNome4.setText("Preço:");

        txtPreco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelNome5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNome5.setText("Quantidade:");

        txtQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnPesquisarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarProduto.setText("Pesquisar");
        btnPesquisarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarProdutoMouseClicked(evt);
            }
        });
        btnPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProdutoActionPerformed(evt);
            }
        });

        btnAdiionarItem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnAdiionarItem.setText("Adicionar Item");
        btnAdiionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdiionarItemActionPerformed(evt);
            }
        });

        btnListaProdutos.setText("Lista de Produtos");
        btnListaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaProdutosActionPerformed(evt);
            }
        });

        btnRemoverItem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnRemoverItem.setText("Remover Item");
        btnRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverItemActionPerformed(evt);
            }
        });

        txtPrecoFormatted.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));

        javax.swing.GroupLayout PainelProdutoLayout = new javax.swing.GroupLayout(PainelProduto);
        PainelProduto.setLayout(PainelProdutoLayout);
        PainelProdutoLayout.setHorizontalGroup(
            PainelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelProdutoLayout.createSequentialGroup()
                .addGroup(PainelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelProdutoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnAdiionarItem)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoverItem))
                    .addGroup(PainelProdutoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PainelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNome4)
                            .addComponent(jLabelNome3)
                            .addComponent(jLabelCpf1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecoFormatted, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDescricao)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelProdutoLayout.createSequentialGroup()
                                    .addGroup(PainelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnListaProdutos)
                                        .addComponent(txtCodigoProduto))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PainelProdutoLayout.createSequentialGroup()
                                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelNome5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelProdutoLayout.setVerticalGroup(
            PainelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelProdutoLayout.createSequentialGroup()
                .addComponent(btnListaProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpf1)
                    .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarProduto))
                .addGap(18, 18, 18)
                .addGroup(PainelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome3)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome4)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecoFormatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(PainelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdiionarItem)
                    .addComponent(btnRemoverItem))
                .addGap(21, 21, 21))
        );

        PainelCliente.setBackground(new java.awt.Color(255, 255, 255));
        PainelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Cliente"));

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNome.setText("Data:");

        txtDataVenda.setEditable(false);
        txtDataVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCpf.setForeground(new java.awt.Color(255, 0, 0));
        jLabelCpf.setText("CPF:");

        txtCpf.setEditable(false);
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelNome1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNome1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNome1.setText("Nome:");

        txtNomeCliente.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteActionPerformed(evt);
            }
        });

        btnPesquisarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarCliente.setText("Pesquisar");
        btnPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarClienteActionPerformed(evt);
            }
        });

        btnListaClientes.setText("Lista de Clientes");
        btnListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaClientesActionPerformed(evt);
            }
        });

        jLabelNome2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNome2.setText("Id:");

        txtIdCliente.setEditable(false);
        txtIdCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelClienteLayout = new javax.swing.GroupLayout(PainelCliente);
        PainelCliente.setLayout(PainelClienteLayout);
        PainelClienteLayout.setHorizontalGroup(
            PainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelClienteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelClienteLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PainelClienteLayout.createSequentialGroup()
                        .addGroup(PainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCpf)
                            .addComponent(jLabelNome1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelClienteLayout.createSequentialGroup()
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PainelClienteLayout.createSequentialGroup()
                                .addGroup(PainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PainelClienteLayout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(btnListaClientes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(PainelClienteLayout.createSequentialGroup()
                                        .addComponent(txtNomeCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(btnPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10))))
        );
        PainelClienteLayout.setVerticalGroup(
            PainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelClienteLayout.createSequentialGroup()
                .addComponent(btnListaClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome1)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarCliente))
                .addGap(22, 22, 22)
                .addGroup(PainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome)
                    .addComponent(txtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome2)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelVendaLayout = new javax.swing.GroupLayout(PainelVenda);
        PainelVenda.setLayout(PainelVendaLayout);
        PainelVendaLayout.setHorizontalGroup(
            PainelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelVendaLayout.createSequentialGroup()
                .addGroup(PainelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelVendaLayout.createSequentialGroup()
                        .addComponent(btnFinalizarCompra)
                        .addGap(85, 85, 85)
                        .addComponent(btnCancelar))
                    .addGroup(PainelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PainelProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PainelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PainelVendaLayout.setVerticalGroup(
            PainelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelVendaLayout.createSequentialGroup()
                .addGroup(PainelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelVendaLayout.createSequentialGroup()
                        .addComponent(PainelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PainelProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelVendaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        PainelGeral.addTab("PDV", PainelVenda);

        PainelClientes.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Nome:");

        txtPesquisarClientess.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPesquisarClientess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarClientessActionPerformed(evt);
            }
        });
        txtPesquisarClientess.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarClientessKeyPressed(evt);
            }
        });

        btnPesquisarClientess.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarClientess.setText("Pesquisar");
        btnPesquisarClientess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarClientessMouseClicked(evt);
            }
        });
        btnPesquisarClientess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarClientessActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        TabelaClientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod:", "Nome:", "CPF:"
            }
        ));
        TabelaClientes.getTableHeader().setReorderingAllowed(false);
        TabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelaClientes);
        if (TabelaClientes.getColumnModel().getColumnCount() > 0) {
            TabelaClientes.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        btnAtualizarListaClientess.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAtualizarListaClientess.setText("ATUALIZAR LISTA DE CLIENTES");
        btnAtualizarListaClientess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarListaClientessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelClientesLayout = new javax.swing.GroupLayout(PainelClientes);
        PainelClientes.setLayout(PainelClientesLayout);
        PainelClientesLayout.setHorizontalGroup(
            PainelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PainelClientesLayout.createSequentialGroup()
                .addGroup(PainelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelClientesLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarClientess, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarClientess))
                    .addGroup(PainelClientesLayout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(btnAtualizarListaClientess)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        PainelClientesLayout.setVerticalGroup(
            PainelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelClientesLayout.createSequentialGroup()
                .addGroup(PainelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPesquisarClientess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarClientess))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizarListaClientess)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PainelGeral.addTab("Lista de Clientes", jPanel3);

        PainelProdutos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Produto:");

        txtpesquisaProdutoss.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpesquisaProdutoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisaProdutossActionPerformed(evt);
            }
        });

        btnPesquisarProdutoss.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarProdutoss.setText("Pesquisar");
        btnPesquisarProdutoss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarProdutossMouseClicked(evt);
            }
        });
        btnPesquisarProdutoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProdutossActionPerformed(evt);
            }
        });

        btnAtualizarListaProdutoss.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAtualizarListaProdutoss.setText("ATUALIZAR LISTA DE PRODUTOS");
        btnAtualizarListaProdutoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarListaProdutossActionPerformed(evt);
            }
        });

        TabelaListaProdutoss.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TabelaListaProdutoss.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código:", "Descrição:", "Preço:", "Quantidade Estoque:"
            }
        ));
        TabelaListaProdutoss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaListaProdutossMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TabelaListaProdutoss);

        javax.swing.GroupLayout PainelProdutosLayout = new javax.swing.GroupLayout(PainelProdutos);
        PainelProdutos.setLayout(PainelProdutosLayout);
        PainelProdutosLayout.setHorizontalGroup(
            PainelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelProdutosLayout.createSequentialGroup()
                .addGroup(PainelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelProdutosLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpesquisaProdutoss, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarProdutoss))
                    .addGroup(PainelProdutosLayout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(btnAtualizarListaProdutoss)))
                .addContainerGap(203, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        PainelProdutosLayout.setVerticalGroup(
            PainelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelProdutosLayout.createSequentialGroup()
                .addGroup(PainelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtpesquisaProdutoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarProdutoss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizarListaProdutoss)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PainelGeral.addTab("Lista de Produtos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PainelGeral)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PainelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelGeral))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //PainelGeral.setSelectedIndex(1);
        txtDataVenda.setText(dtf.format(LocalDateTime.now()));
        Utilitarios.setCellsAlignment(TabelaItens, SwingConstants.CENTER);
        Utilitarios.setCellsAlignment(TabelaListaProdutoss, SwingConstants.CENTER);
        Utilitarios.setCellsAlignment(TabelaClientes, SwingConstants.CENTER);
        listarClientes();
        listarProdutos();

    }//GEN-LAST:event_formWindowActivated

    private void btnPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarClienteActionPerformed
        // TODO add your handling code here:
        ClienteDAO dao = new ClienteDAO();
        obj = dao.listarPorNomes(txtNomeCliente.getText());
        txtCpf.setText(obj.getCpf());
        txtIdCliente.setText(String.valueOf(obj.getId()));

    }//GEN-LAST:event_btnPesquisarClienteActionPerformed

    private void adicionarItem(){
        try {
            qtd = Integer.parseInt(txtQuantidade.getText());
            preco = Double.parseDouble(txtPreco.getText());
            subtotal = qtd * preco;
            total += subtotal;
            txtTotalDaVenda.setText(String.valueOf(total));

            //Adicionar Itens ao Carrinho
            carrinhoVenda = (DefaultTableModel) TabelaItens.getModel();
            carrinhoVenda.addRow(new Object[]{
                txtCodigoProduto.getText(),
                txtDescricao.getText(),
                txtQuantidade.getText(),
                txtPreco.getText(),
                subtotal
            });
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(null, "Informe um Produto!");
        }
        txtCodigoProduto.setText("");
        txtDescricao.setText("");
        txtPreco.setText("");
        txtCodigoProduto.requestFocusInWindow();
        txtQuantidade.setText("1");
    }
    
    private void btnAdiionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdiionarItemActionPerformed
        // TODO add your handling code here:
        adicionarItem();

    }//GEN-LAST:event_btnAdiionarItemActionPerformed

    private void btnPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdutoActionPerformed
        // TODO add your handling code here:
        if(txtCodigoProduto.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe um código de produto para Pesquisar");
    }else{
        ProdutoModel obj = new ProdutoModel();
        ProdutoDAO pDao = new ProdutoDAO();

        obj = pDao.listarPorCod(Integer.parseInt(txtCodigoProduto.getText()));
        txtDescricao.setText(obj.getDescricao());
        txtPreco.setText(String.valueOf(obj.getPreco()));
        txtQuantidade.setText("1");
        txtPrecoFormatted.setText(txtPreco.getText());
        }
    }//GEN-LAST:event_btnPesquisarProdutoActionPerformed

    private void btnPesquisarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarProdutoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarProdutoMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraActionPerformed
        // TODO add your handling code here:
        if (txtNomeCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha um Cliente!");
        } else {
            if (TabelaItens.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Adicione um produto ao carrinho!");
                PainelGeral.setSelectedIndex(0);
            } else {
                PagamentoView pv = new PagamentoView();
                pv.txtTotal.setText(String.valueOf(total));
                pv.txtCartao.setText("0");
                pv.txtDinheiro.setText("0");
                pv.cliente = obj;
                pv.carrinhoPagamento = carrinhoVenda;
                pv.setVisible(true);
                //this.dispose();
            }
        }
    }//GEN-LAST:event_btnFinalizarCompraActionPerformed

    private void btnFinalizarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarCompraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarCompraMouseClicked

    private void txtCodigoProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProdutoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ProdutoModel obj = new ProdutoModel();
            ProdutoDAO pDao = new ProdutoDAO();

            obj = pDao.listarPorCod(Integer.parseInt(txtCodigoProduto.getText()));
            txtDescricao.setText(obj.getDescricao());
            txtPreco.setText(String.valueOf(obj.getPreco()));
            txtQuantidade.setText("1");
        }
    }//GEN-LAST:event_txtCodigoProdutoKeyPressed

    private void txtCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProdutoActionPerformed

    private void txtNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteActionPerformed

    private void btnListaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaProdutosActionPerformed
        // TODO add your handling code here:
        PainelGeral.setSelectedIndex(2);
    }//GEN-LAST:event_btnListaProdutosActionPerformed

    private void btnListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaClientesActionPerformed
        // TODO add your handling code here:
        PainelGeral.setSelectedIndex(1);
    }//GEN-LAST:event_btnListaClientesActionPerformed

    private void txtPesquisarClientessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarClientessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarClientessActionPerformed

    private void txtPesquisarClientessKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarClientessKeyPressed

        String nome = "%" + txtPesquisarClientess.getText() + "%";
        ClienteDAO dao = new ClienteDAO();
        List<ClienteModel> lista = dao.listarPorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) TabelaClientes.getModel();
        dados.setNumRows(0);

        lista.forEach(c -> {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCpf()
            });
        });
    }//GEN-LAST:event_txtPesquisarClientessKeyPressed

    private void btnPesquisarClientessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarClientessMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        String nome = "%" + txtPesquisarClientess.getText() + "%";
        ClienteDAO dao = new ClienteDAO();
        List<ClienteModel> lista = dao.listarPorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) TabelaClientes.getModel();
        dados.setNumRows(0);

        lista.forEach(c -> {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCpf()
            });
        });
    }//GEN-LAST:event_btnPesquisarClientessMouseClicked

    private void btnPesquisarClientessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarClientessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarClientessActionPerformed

    private void TabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaClientesMouseClicked
        // TODO add your handling
        PainelGeral.setSelectedIndex(0);
        //txtIdCliente.setText(String.valueOf(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 0)));
        txtNomeCliente.setText(String.valueOf(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 1)));
        //txtCpf.setText(String.valueOf(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 2)));

        ClienteDAO dao = new ClienteDAO();
        obj = dao.listarPorNomes(txtNomeCliente.getText());
        txtCpf.setText(obj.getCpf());
        txtIdCliente.setText(String.valueOf(obj.getId()));

    }//GEN-LAST:event_TabelaClientesMouseClicked

    private void btnAtualizarListaClientessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarListaClientessActionPerformed
        // TODO add your handling code here:
        txtPesquisarClientess.setText("");
        listarClientes();
    }//GEN-LAST:event_btnAtualizarListaClientessActionPerformed

    private void TabelaItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaItensMouseClicked
        // TODO add your handling code here:
        

    }//GEN-LAST:event_TabelaItensMouseClicked

    private void txtpesquisaProdutossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisaProdutossActionPerformed
        // TODO add your handling code here:   
        String nome = "%" + txtpesquisaProdutoss.getText() + "%";
        ProdutoDAO pDao = new ProdutoDAO();
        List<ProdutoModel> lista = pDao.listarPorDesc(nome);
        DefaultTableModel dados = (DefaultTableModel) TabelaListaProdutoss.getModel();
        dados.setNumRows(0);

        lista.forEach(c -> {
            dados.addRow(new Object[]{
                c.getId(),
                c.getDescricao(),
                c.getPreco(),
                c.getQtd_estoque()
            });
        });
    }//GEN-LAST:event_txtpesquisaProdutossActionPerformed

    private void btnPesquisarProdutossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarProdutossMouseClicked
        // TODO add your handling code here:
        String nome = "%" + txtpesquisaProdutoss.getText() + "%";
        ProdutoDAO pDao = new ProdutoDAO();
        List<ProdutoModel> lista = pDao.listarPorDesc(nome);
        DefaultTableModel dados = (DefaultTableModel) TabelaListaProdutoss.getModel();
        dados.setNumRows(0);

        lista.forEach(c -> {
            dados.addRow(new Object[]{
                c.getId(),
                c.getDescricao(),
                c.getPreco(),
                c.getQtd_estoque()
            });
        });
    }//GEN-LAST:event_btnPesquisarProdutossMouseClicked

    private void btnPesquisarProdutossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdutossActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnPesquisarProdutossActionPerformed

    private void btnAtualizarListaProdutossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarListaProdutossActionPerformed
        // TODO add your handling code here:
        listarProdutos();
        txtpesquisaProdutoss.setText("");
    }//GEN-LAST:event_btnAtualizarListaProdutossActionPerformed

    private void TabelaListaProdutossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaListaProdutossMouseClicked
        // TODO add your handling code here:
        PainelGeral.setSelectedIndex(0);
        txtCodigoProduto.setText(String.valueOf(TabelaListaProdutoss.getValueAt(TabelaListaProdutoss.getSelectedRow(), 0)));
        txtDescricao.setText(String.valueOf(TabelaListaProdutoss.getValueAt(TabelaListaProdutoss.getSelectedRow(), 1)));
        txtPreco.setText(String.valueOf(TabelaListaProdutoss.getValueAt(TabelaListaProdutoss.getSelectedRow(), 2)));
        txtQuantidade.setText("1");
    }//GEN-LAST:event_TabelaListaProdutossMouseClicked

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void btnRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItemActionPerformed
        // TODO add your handling code here:
        try{
        double subTotal;
        subTotal = Double.parseDouble(TabelaItens.getValueAt(TabelaItens.getSelectedRow(), 4).toString());
        total-=subTotal;
        carrinhoVenda.removeRow(TabelaItens.getSelectedRow());
        txtTotalDaVenda.setText(String.valueOf(total));
        }catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Selecione um produto para remover do Carrinho!");
        }
    }//GEN-LAST:event_btnRemoverItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelCliente;
    private javax.swing.JPanel PainelClientes;
    private javax.swing.JTabbedPane PainelGeral;
    private javax.swing.JPanel PainelLogo;
    private javax.swing.JPanel PainelProduto;
    private javax.swing.JPanel PainelProdutos;
    private javax.swing.JPanel PainelVenda;
    public javax.swing.JTable TabelaClientes;
    private javax.swing.JTable TabelaItens;
    private javax.swing.JTable TabelaListaProdutoss;
    private javax.swing.JButton btnAdiionarItem;
    private javax.swing.JButton btnAtualizarListaClientess;
    private javax.swing.JButton btnAtualizarListaProdutoss;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JButton btnListaClientes;
    private javax.swing.JButton btnListaProdutos;
    private javax.swing.JButton btnPesquisarCliente;
    private javax.swing.JButton btnPesquisarClientess;
    private javax.swing.JButton btnPesquisarProduto;
    private javax.swing.JButton btnPesquisarProdutoss;
    private javax.swing.JButton btnRemoverItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelCpf1;
    private javax.swing.JLabel jLabelCpf2;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNome1;
    private javax.swing.JLabel jLabelNome2;
    private javax.swing.JLabel jLabelNome3;
    private javax.swing.JLabel jLabelNome4;
    private javax.swing.JLabel jLabelNome5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtDataVenda;
    private javax.swing.JTextField txtDescricao;
    public javax.swing.JTextField txtIdCliente;
    public javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtPesquisarClientess;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JFormattedTextField txtPrecoFormatted;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtTotalDaVenda;
    private javax.swing.JTextField txtpesquisaProdutoss;
    // End of variables declaration//GEN-END:variables
}
